# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.29.3/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.29.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/lap14443/Projects/CPP-Core

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/lap14443/Projects/CPP-Core

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.29.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.29.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/lap14443/Projects/CPP-Core/CMakeFiles /Users/lap14443/Projects/CPP-Core//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/lap14443/Projects/CPP-Core/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named googletest

# Build rule for target.
googletest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 googletest
.PHONY : googletest

# fast build rule for target.
googletest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/googletest.dir/build.make CMakeFiles/googletest.dir/build
.PHONY : googletest/fast

#=============================================================================
# Target rules for targets named extra_long_factorial

# Build rule for target.
extra_long_factorial: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 extra_long_factorial
.PHONY : extra_long_factorial

# fast build rule for target.
extra_long_factorial/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extra_long_factorial.dir/build.make CMakeFiles/extra_long_factorial.dir/build
.PHONY : extra_long_factorial/fast

#=============================================================================
# Target rules for targets named merge_sort

# Build rule for target.
merge_sort: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 merge_sort
.PHONY : merge_sort

# fast build rule for target.
merge_sort/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/merge_sort.dir/build.make CMakeFiles/merge_sort.dir/build
.PHONY : merge_sort/fast

#=============================================================================
# Target rules for targets named heap_sort

# Build rule for target.
heap_sort: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 heap_sort
.PHONY : heap_sort

# fast build rule for target.
heap_sort/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/heap_sort.dir/build.make CMakeFiles/heap_sort.dir/build
.PHONY : heap_sort/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named test_extra_long_factorial

# Build rule for target.
test_extra_long_factorial: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_extra_long_factorial
.PHONY : test_extra_long_factorial

# fast build rule for target.
test_extra_long_factorial/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_extra_long_factorial.dir/build.make CMakeFiles/test_extra_long_factorial.dir/build
.PHONY : test_extra_long_factorial/fast

#=============================================================================
# Target rules for targets named test_merge_sort

# Build rule for target.
test_merge_sort: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_merge_sort
.PHONY : test_merge_sort

# fast build rule for target.
test_merge_sort/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_merge_sort.dir/build.make CMakeFiles/test_merge_sort.dir/build
.PHONY : test_merge_sort/fast

#=============================================================================
# Target rules for targets named test_heap_sort

# Build rule for target.
test_heap_sort: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_heap_sort
.PHONY : test_heap_sort

# fast build rule for target.
test_heap_sort/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_heap_sort.dir/build.make CMakeFiles/test_heap_sort.dir/build
.PHONY : test_heap_sort/fast

Algorithms/HeapSort/heap_sort.o: Algorithms/HeapSort/heap_sort.cpp.o
.PHONY : Algorithms/HeapSort/heap_sort.o

# target to build an object file
Algorithms/HeapSort/heap_sort.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/heap_sort.dir/build.make CMakeFiles/heap_sort.dir/Algorithms/HeapSort/heap_sort.cpp.o
.PHONY : Algorithms/HeapSort/heap_sort.cpp.o

Algorithms/HeapSort/heap_sort.i: Algorithms/HeapSort/heap_sort.cpp.i
.PHONY : Algorithms/HeapSort/heap_sort.i

# target to preprocess a source file
Algorithms/HeapSort/heap_sort.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/heap_sort.dir/build.make CMakeFiles/heap_sort.dir/Algorithms/HeapSort/heap_sort.cpp.i
.PHONY : Algorithms/HeapSort/heap_sort.cpp.i

Algorithms/HeapSort/heap_sort.s: Algorithms/HeapSort/heap_sort.cpp.s
.PHONY : Algorithms/HeapSort/heap_sort.s

# target to generate assembly for a file
Algorithms/HeapSort/heap_sort.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/heap_sort.dir/build.make CMakeFiles/heap_sort.dir/Algorithms/HeapSort/heap_sort.cpp.s
.PHONY : Algorithms/HeapSort/heap_sort.cpp.s

Algorithms/HeapSort/test_heap_sort.o: Algorithms/HeapSort/test_heap_sort.cpp.o
.PHONY : Algorithms/HeapSort/test_heap_sort.o

# target to build an object file
Algorithms/HeapSort/test_heap_sort.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_heap_sort.dir/build.make CMakeFiles/test_heap_sort.dir/Algorithms/HeapSort/test_heap_sort.cpp.o
.PHONY : Algorithms/HeapSort/test_heap_sort.cpp.o

Algorithms/HeapSort/test_heap_sort.i: Algorithms/HeapSort/test_heap_sort.cpp.i
.PHONY : Algorithms/HeapSort/test_heap_sort.i

# target to preprocess a source file
Algorithms/HeapSort/test_heap_sort.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_heap_sort.dir/build.make CMakeFiles/test_heap_sort.dir/Algorithms/HeapSort/test_heap_sort.cpp.i
.PHONY : Algorithms/HeapSort/test_heap_sort.cpp.i

Algorithms/HeapSort/test_heap_sort.s: Algorithms/HeapSort/test_heap_sort.cpp.s
.PHONY : Algorithms/HeapSort/test_heap_sort.s

# target to generate assembly for a file
Algorithms/HeapSort/test_heap_sort.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_heap_sort.dir/build.make CMakeFiles/test_heap_sort.dir/Algorithms/HeapSort/test_heap_sort.cpp.s
.PHONY : Algorithms/HeapSort/test_heap_sort.cpp.s

Algorithms/MergeSort/merge_sort.o: Algorithms/MergeSort/merge_sort.cpp.o
.PHONY : Algorithms/MergeSort/merge_sort.o

# target to build an object file
Algorithms/MergeSort/merge_sort.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/merge_sort.dir/build.make CMakeFiles/merge_sort.dir/Algorithms/MergeSort/merge_sort.cpp.o
.PHONY : Algorithms/MergeSort/merge_sort.cpp.o

Algorithms/MergeSort/merge_sort.i: Algorithms/MergeSort/merge_sort.cpp.i
.PHONY : Algorithms/MergeSort/merge_sort.i

# target to preprocess a source file
Algorithms/MergeSort/merge_sort.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/merge_sort.dir/build.make CMakeFiles/merge_sort.dir/Algorithms/MergeSort/merge_sort.cpp.i
.PHONY : Algorithms/MergeSort/merge_sort.cpp.i

Algorithms/MergeSort/merge_sort.s: Algorithms/MergeSort/merge_sort.cpp.s
.PHONY : Algorithms/MergeSort/merge_sort.s

# target to generate assembly for a file
Algorithms/MergeSort/merge_sort.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/merge_sort.dir/build.make CMakeFiles/merge_sort.dir/Algorithms/MergeSort/merge_sort.cpp.s
.PHONY : Algorithms/MergeSort/merge_sort.cpp.s

Algorithms/MergeSort/test_merge_sort.o: Algorithms/MergeSort/test_merge_sort.cpp.o
.PHONY : Algorithms/MergeSort/test_merge_sort.o

# target to build an object file
Algorithms/MergeSort/test_merge_sort.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_merge_sort.dir/build.make CMakeFiles/test_merge_sort.dir/Algorithms/MergeSort/test_merge_sort.cpp.o
.PHONY : Algorithms/MergeSort/test_merge_sort.cpp.o

Algorithms/MergeSort/test_merge_sort.i: Algorithms/MergeSort/test_merge_sort.cpp.i
.PHONY : Algorithms/MergeSort/test_merge_sort.i

# target to preprocess a source file
Algorithms/MergeSort/test_merge_sort.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_merge_sort.dir/build.make CMakeFiles/test_merge_sort.dir/Algorithms/MergeSort/test_merge_sort.cpp.i
.PHONY : Algorithms/MergeSort/test_merge_sort.cpp.i

Algorithms/MergeSort/test_merge_sort.s: Algorithms/MergeSort/test_merge_sort.cpp.s
.PHONY : Algorithms/MergeSort/test_merge_sort.s

# target to generate assembly for a file
Algorithms/MergeSort/test_merge_sort.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_merge_sort.dir/build.make CMakeFiles/test_merge_sort.dir/Algorithms/MergeSort/test_merge_sort.cpp.s
.PHONY : Algorithms/MergeSort/test_merge_sort.cpp.s

ProblemSolving/ExtraLongFactorial/extra_long_factorial.o: ProblemSolving/ExtraLongFactorial/extra_long_factorial.cpp.o
.PHONY : ProblemSolving/ExtraLongFactorial/extra_long_factorial.o

# target to build an object file
ProblemSolving/ExtraLongFactorial/extra_long_factorial.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extra_long_factorial.dir/build.make CMakeFiles/extra_long_factorial.dir/ProblemSolving/ExtraLongFactorial/extra_long_factorial.cpp.o
.PHONY : ProblemSolving/ExtraLongFactorial/extra_long_factorial.cpp.o

ProblemSolving/ExtraLongFactorial/extra_long_factorial.i: ProblemSolving/ExtraLongFactorial/extra_long_factorial.cpp.i
.PHONY : ProblemSolving/ExtraLongFactorial/extra_long_factorial.i

# target to preprocess a source file
ProblemSolving/ExtraLongFactorial/extra_long_factorial.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extra_long_factorial.dir/build.make CMakeFiles/extra_long_factorial.dir/ProblemSolving/ExtraLongFactorial/extra_long_factorial.cpp.i
.PHONY : ProblemSolving/ExtraLongFactorial/extra_long_factorial.cpp.i

ProblemSolving/ExtraLongFactorial/extra_long_factorial.s: ProblemSolving/ExtraLongFactorial/extra_long_factorial.cpp.s
.PHONY : ProblemSolving/ExtraLongFactorial/extra_long_factorial.s

# target to generate assembly for a file
ProblemSolving/ExtraLongFactorial/extra_long_factorial.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extra_long_factorial.dir/build.make CMakeFiles/extra_long_factorial.dir/ProblemSolving/ExtraLongFactorial/extra_long_factorial.cpp.s
.PHONY : ProblemSolving/ExtraLongFactorial/extra_long_factorial.cpp.s

ProblemSolving/ExtraLongFactorial/main.o: ProblemSolving/ExtraLongFactorial/main.cpp.o
.PHONY : ProblemSolving/ExtraLongFactorial/main.o

# target to build an object file
ProblemSolving/ExtraLongFactorial/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/ProblemSolving/ExtraLongFactorial/main.cpp.o
.PHONY : ProblemSolving/ExtraLongFactorial/main.cpp.o

ProblemSolving/ExtraLongFactorial/main.i: ProblemSolving/ExtraLongFactorial/main.cpp.i
.PHONY : ProblemSolving/ExtraLongFactorial/main.i

# target to preprocess a source file
ProblemSolving/ExtraLongFactorial/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/ProblemSolving/ExtraLongFactorial/main.cpp.i
.PHONY : ProblemSolving/ExtraLongFactorial/main.cpp.i

ProblemSolving/ExtraLongFactorial/main.s: ProblemSolving/ExtraLongFactorial/main.cpp.s
.PHONY : ProblemSolving/ExtraLongFactorial/main.s

# target to generate assembly for a file
ProblemSolving/ExtraLongFactorial/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/ProblemSolving/ExtraLongFactorial/main.cpp.s
.PHONY : ProblemSolving/ExtraLongFactorial/main.cpp.s

ProblemSolving/ExtraLongFactorial/test_extra_long_factorial.o: ProblemSolving/ExtraLongFactorial/test_extra_long_factorial.cpp.o
.PHONY : ProblemSolving/ExtraLongFactorial/test_extra_long_factorial.o

# target to build an object file
ProblemSolving/ExtraLongFactorial/test_extra_long_factorial.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_extra_long_factorial.dir/build.make CMakeFiles/test_extra_long_factorial.dir/ProblemSolving/ExtraLongFactorial/test_extra_long_factorial.cpp.o
.PHONY : ProblemSolving/ExtraLongFactorial/test_extra_long_factorial.cpp.o

ProblemSolving/ExtraLongFactorial/test_extra_long_factorial.i: ProblemSolving/ExtraLongFactorial/test_extra_long_factorial.cpp.i
.PHONY : ProblemSolving/ExtraLongFactorial/test_extra_long_factorial.i

# target to preprocess a source file
ProblemSolving/ExtraLongFactorial/test_extra_long_factorial.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_extra_long_factorial.dir/build.make CMakeFiles/test_extra_long_factorial.dir/ProblemSolving/ExtraLongFactorial/test_extra_long_factorial.cpp.i
.PHONY : ProblemSolving/ExtraLongFactorial/test_extra_long_factorial.cpp.i

ProblemSolving/ExtraLongFactorial/test_extra_long_factorial.s: ProblemSolving/ExtraLongFactorial/test_extra_long_factorial.cpp.s
.PHONY : ProblemSolving/ExtraLongFactorial/test_extra_long_factorial.s

# target to generate assembly for a file
ProblemSolving/ExtraLongFactorial/test_extra_long_factorial.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_extra_long_factorial.dir/build.make CMakeFiles/test_extra_long_factorial.dir/ProblemSolving/ExtraLongFactorial/test_extra_long_factorial.cpp.s
.PHONY : ProblemSolving/ExtraLongFactorial/test_extra_long_factorial.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... googletest"
	@echo "... extra_long_factorial"
	@echo "... heap_sort"
	@echo "... main"
	@echo "... merge_sort"
	@echo "... test_extra_long_factorial"
	@echo "... test_heap_sort"
	@echo "... test_merge_sort"
	@echo "... Algorithms/HeapSort/heap_sort.o"
	@echo "... Algorithms/HeapSort/heap_sort.i"
	@echo "... Algorithms/HeapSort/heap_sort.s"
	@echo "... Algorithms/HeapSort/test_heap_sort.o"
	@echo "... Algorithms/HeapSort/test_heap_sort.i"
	@echo "... Algorithms/HeapSort/test_heap_sort.s"
	@echo "... Algorithms/MergeSort/merge_sort.o"
	@echo "... Algorithms/MergeSort/merge_sort.i"
	@echo "... Algorithms/MergeSort/merge_sort.s"
	@echo "... Algorithms/MergeSort/test_merge_sort.o"
	@echo "... Algorithms/MergeSort/test_merge_sort.i"
	@echo "... Algorithms/MergeSort/test_merge_sort.s"
	@echo "... ProblemSolving/ExtraLongFactorial/extra_long_factorial.o"
	@echo "... ProblemSolving/ExtraLongFactorial/extra_long_factorial.i"
	@echo "... ProblemSolving/ExtraLongFactorial/extra_long_factorial.s"
	@echo "... ProblemSolving/ExtraLongFactorial/main.o"
	@echo "... ProblemSolving/ExtraLongFactorial/main.i"
	@echo "... ProblemSolving/ExtraLongFactorial/main.s"
	@echo "... ProblemSolving/ExtraLongFactorial/test_extra_long_factorial.o"
	@echo "... ProblemSolving/ExtraLongFactorial/test_extra_long_factorial.i"
	@echo "... ProblemSolving/ExtraLongFactorial/test_extra_long_factorial.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

