# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.29.3/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.29.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/lap14443/Projects/Cpp-Core

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/lap14443/Projects/Cpp-Core

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.29.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.29.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/lap14443/Projects/Cpp-Core/CMakeFiles /Users/lap14443/Projects/Cpp-Core//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/lap14443/Projects/Cpp-Core/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named googletest

# Build rule for target.
googletest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 googletest
.PHONY : googletest

# fast build rule for target.
googletest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/googletest.dir/build.make CMakeFiles/googletest.dir/build
.PHONY : googletest/fast

#=============================================================================
# Target rules for targets named binary_tree

# Build rule for target.
binary_tree: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 binary_tree
.PHONY : binary_tree

# fast build rule for target.
binary_tree/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary_tree.dir/build.make CMakeFiles/binary_tree.dir/build
.PHONY : binary_tree/fast

#=============================================================================
# Target rules for targets named heap_sort

# Build rule for target.
heap_sort: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 heap_sort
.PHONY : heap_sort

# fast build rule for target.
heap_sort/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/heap_sort.dir/build.make CMakeFiles/heap_sort.dir/build
.PHONY : heap_sort/fast

#=============================================================================
# Target rules for targets named linked_list

# Build rule for target.
linked_list: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 linked_list
.PHONY : linked_list

# fast build rule for target.
linked_list/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linked_list.dir/build.make CMakeFiles/linked_list.dir/build
.PHONY : linked_list/fast

#=============================================================================
# Target rules for targets named merge_sort

# Build rule for target.
merge_sort: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 merge_sort
.PHONY : merge_sort

# fast build rule for target.
merge_sort/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/merge_sort.dir/build.make CMakeFiles/merge_sort.dir/build
.PHONY : merge_sort/fast

#=============================================================================
# Target rules for targets named mrroot501_hash_table

# Build rule for target.
mrroot501_hash_table: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mrroot501_hash_table
.PHONY : mrroot501_hash_table

# fast build rule for target.
mrroot501_hash_table/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mrroot501_hash_table.dir/build.make CMakeFiles/mrroot501_hash_table.dir/build
.PHONY : mrroot501_hash_table/fast

#=============================================================================
# Target rules for targets named segment_tree

# Build rule for target.
segment_tree: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 segment_tree
.PHONY : segment_tree

# fast build rule for target.
segment_tree/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/segment_tree.dir/build.make CMakeFiles/segment_tree.dir/build
.PHONY : segment_tree/fast

#=============================================================================
# Target rules for targets named quick_sort

# Build rule for target.
quick_sort: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quick_sort
.PHONY : quick_sort

# fast build rule for target.
quick_sort/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quick_sort.dir/build.make CMakeFiles/quick_sort.dir/build
.PHONY : quick_sort/fast

#=============================================================================
# Target rules for targets named extra_long_factorial_main

# Build rule for target.
extra_long_factorial_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 extra_long_factorial_main
.PHONY : extra_long_factorial_main

# fast build rule for target.
extra_long_factorial_main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extra_long_factorial_main.dir/build.make CMakeFiles/extra_long_factorial_main.dir/build
.PHONY : extra_long_factorial_main/fast

#=============================================================================
# Target rules for targets named merge_sort_external_main

# Build rule for target.
merge_sort_external_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 merge_sort_external_main
.PHONY : merge_sort_external_main

# fast build rule for target.
merge_sort_external_main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/merge_sort_external_main.dir/build.make CMakeFiles/merge_sort_external_main.dir/build
.PHONY : merge_sort_external_main/fast

#=============================================================================
# Target rules for targets named binary_tree_main

# Build rule for target.
binary_tree_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 binary_tree_main
.PHONY : binary_tree_main

# fast build rule for target.
binary_tree_main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary_tree_main.dir/build.make CMakeFiles/binary_tree_main.dir/build
.PHONY : binary_tree_main/fast

#=============================================================================
# Target rules for targets named segment_tree_main

# Build rule for target.
segment_tree_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 segment_tree_main
.PHONY : segment_tree_main

# fast build rule for target.
segment_tree_main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/segment_tree_main.dir/build.make CMakeFiles/segment_tree_main.dir/build
.PHONY : segment_tree_main/fast

#=============================================================================
# Target rules for targets named mrroot501_hash_table_main

# Build rule for target.
mrroot501_hash_table_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mrroot501_hash_table_main
.PHONY : mrroot501_hash_table_main

# fast build rule for target.
mrroot501_hash_table_main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mrroot501_hash_table_main.dir/build.make CMakeFiles/mrroot501_hash_table_main.dir/build
.PHONY : mrroot501_hash_table_main/fast

#=============================================================================
# Target rules for targets named linked_list_main

# Build rule for target.
linked_list_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 linked_list_main
.PHONY : linked_list_main

# fast build rule for target.
linked_list_main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linked_list_main.dir/build.make CMakeFiles/linked_list_main.dir/build
.PHONY : linked_list_main/fast

#=============================================================================
# Target rules for targets named quick_sort_main

# Build rule for target.
quick_sort_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quick_sort_main
.PHONY : quick_sort_main

# fast build rule for target.
quick_sort_main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quick_sort_main.dir/build.make CMakeFiles/quick_sort_main.dir/build
.PHONY : quick_sort_main/fast

#=============================================================================
# Target rules for targets named test_extra_long_factorial

# Build rule for target.
test_extra_long_factorial: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_extra_long_factorial
.PHONY : test_extra_long_factorial

# fast build rule for target.
test_extra_long_factorial/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_extra_long_factorial.dir/build.make CMakeFiles/test_extra_long_factorial.dir/build
.PHONY : test_extra_long_factorial/fast

#=============================================================================
# Target rules for targets named test_merge_sort

# Build rule for target.
test_merge_sort: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_merge_sort
.PHONY : test_merge_sort

# fast build rule for target.
test_merge_sort/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_merge_sort.dir/build.make CMakeFiles/test_merge_sort.dir/build
.PHONY : test_merge_sort/fast

#=============================================================================
# Target rules for targets named test_heap_sort

# Build rule for target.
test_heap_sort: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_heap_sort
.PHONY : test_heap_sort

# fast build rule for target.
test_heap_sort/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_heap_sort.dir/build.make CMakeFiles/test_heap_sort.dir/build
.PHONY : test_heap_sort/fast

#=============================================================================
# Target rules for targets named test_longest_common_subsequence

# Build rule for target.
test_longest_common_subsequence: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_longest_common_subsequence
.PHONY : test_longest_common_subsequence

# fast build rule for target.
test_longest_common_subsequence/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_longest_common_subsequence.dir/build.make CMakeFiles/test_longest_common_subsequence.dir/build
.PHONY : test_longest_common_subsequence/fast

#=============================================================================
# Target rules for targets named test_longest_palindromic_substring

# Build rule for target.
test_longest_palindromic_substring: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_longest_palindromic_substring
.PHONY : test_longest_palindromic_substring

# fast build rule for target.
test_longest_palindromic_substring/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_longest_palindromic_substring.dir/build.make CMakeFiles/test_longest_palindromic_substring.dir/build
.PHONY : test_longest_palindromic_substring/fast

#=============================================================================
# Target rules for targets named test_range_sum_queries_without_updates

# Build rule for target.
test_range_sum_queries_without_updates: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_range_sum_queries_without_updates
.PHONY : test_range_sum_queries_without_updates

# fast build rule for target.
test_range_sum_queries_without_updates/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_range_sum_queries_without_updates.dir/build.make CMakeFiles/test_range_sum_queries_without_updates.dir/build
.PHONY : test_range_sum_queries_without_updates/fast

#=============================================================================
# Target rules for targets named test_find_largest_value_in_tree_row

# Build rule for target.
test_find_largest_value_in_tree_row: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_find_largest_value_in_tree_row
.PHONY : test_find_largest_value_in_tree_row

# fast build rule for target.
test_find_largest_value_in_tree_row/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_find_largest_value_in_tree_row.dir/build.make CMakeFiles/test_find_largest_value_in_tree_row.dir/build
.PHONY : test_find_largest_value_in_tree_row/fast

#=============================================================================
# Target rules for targets named test_shortest_path_in_binary_matrix

# Build rule for target.
test_shortest_path_in_binary_matrix: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_shortest_path_in_binary_matrix
.PHONY : test_shortest_path_in_binary_matrix

# fast build rule for target.
test_shortest_path_in_binary_matrix/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_shortest_path_in_binary_matrix.dir/build.make CMakeFiles/test_shortest_path_in_binary_matrix.dir/build
.PHONY : test_shortest_path_in_binary_matrix/fast

Algorithms/HeapSort/heap_sort.o: Algorithms/HeapSort/heap_sort.cpp.o
.PHONY : Algorithms/HeapSort/heap_sort.o

# target to build an object file
Algorithms/HeapSort/heap_sort.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/heap_sort.dir/build.make CMakeFiles/heap_sort.dir/Algorithms/HeapSort/heap_sort.cpp.o
.PHONY : Algorithms/HeapSort/heap_sort.cpp.o

Algorithms/HeapSort/heap_sort.i: Algorithms/HeapSort/heap_sort.cpp.i
.PHONY : Algorithms/HeapSort/heap_sort.i

# target to preprocess a source file
Algorithms/HeapSort/heap_sort.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/heap_sort.dir/build.make CMakeFiles/heap_sort.dir/Algorithms/HeapSort/heap_sort.cpp.i
.PHONY : Algorithms/HeapSort/heap_sort.cpp.i

Algorithms/HeapSort/heap_sort.s: Algorithms/HeapSort/heap_sort.cpp.s
.PHONY : Algorithms/HeapSort/heap_sort.s

# target to generate assembly for a file
Algorithms/HeapSort/heap_sort.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/heap_sort.dir/build.make CMakeFiles/heap_sort.dir/Algorithms/HeapSort/heap_sort.cpp.s
.PHONY : Algorithms/HeapSort/heap_sort.cpp.s

Algorithms/HeapSort/test_heap_sort.o: Algorithms/HeapSort/test_heap_sort.cpp.o
.PHONY : Algorithms/HeapSort/test_heap_sort.o

# target to build an object file
Algorithms/HeapSort/test_heap_sort.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_heap_sort.dir/build.make CMakeFiles/test_heap_sort.dir/Algorithms/HeapSort/test_heap_sort.cpp.o
.PHONY : Algorithms/HeapSort/test_heap_sort.cpp.o

Algorithms/HeapSort/test_heap_sort.i: Algorithms/HeapSort/test_heap_sort.cpp.i
.PHONY : Algorithms/HeapSort/test_heap_sort.i

# target to preprocess a source file
Algorithms/HeapSort/test_heap_sort.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_heap_sort.dir/build.make CMakeFiles/test_heap_sort.dir/Algorithms/HeapSort/test_heap_sort.cpp.i
.PHONY : Algorithms/HeapSort/test_heap_sort.cpp.i

Algorithms/HeapSort/test_heap_sort.s: Algorithms/HeapSort/test_heap_sort.cpp.s
.PHONY : Algorithms/HeapSort/test_heap_sort.s

# target to generate assembly for a file
Algorithms/HeapSort/test_heap_sort.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_heap_sort.dir/build.make CMakeFiles/test_heap_sort.dir/Algorithms/HeapSort/test_heap_sort.cpp.s
.PHONY : Algorithms/HeapSort/test_heap_sort.cpp.s

Algorithms/MergeSort/merge_sort.o: Algorithms/MergeSort/merge_sort.cpp.o
.PHONY : Algorithms/MergeSort/merge_sort.o

# target to build an object file
Algorithms/MergeSort/merge_sort.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/merge_sort.dir/build.make CMakeFiles/merge_sort.dir/Algorithms/MergeSort/merge_sort.cpp.o
.PHONY : Algorithms/MergeSort/merge_sort.cpp.o

Algorithms/MergeSort/merge_sort.i: Algorithms/MergeSort/merge_sort.cpp.i
.PHONY : Algorithms/MergeSort/merge_sort.i

# target to preprocess a source file
Algorithms/MergeSort/merge_sort.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/merge_sort.dir/build.make CMakeFiles/merge_sort.dir/Algorithms/MergeSort/merge_sort.cpp.i
.PHONY : Algorithms/MergeSort/merge_sort.cpp.i

Algorithms/MergeSort/merge_sort.s: Algorithms/MergeSort/merge_sort.cpp.s
.PHONY : Algorithms/MergeSort/merge_sort.s

# target to generate assembly for a file
Algorithms/MergeSort/merge_sort.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/merge_sort.dir/build.make CMakeFiles/merge_sort.dir/Algorithms/MergeSort/merge_sort.cpp.s
.PHONY : Algorithms/MergeSort/merge_sort.cpp.s

Algorithms/MergeSort/test_merge_sort.o: Algorithms/MergeSort/test_merge_sort.cpp.o
.PHONY : Algorithms/MergeSort/test_merge_sort.o

# target to build an object file
Algorithms/MergeSort/test_merge_sort.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_merge_sort.dir/build.make CMakeFiles/test_merge_sort.dir/Algorithms/MergeSort/test_merge_sort.cpp.o
.PHONY : Algorithms/MergeSort/test_merge_sort.cpp.o

Algorithms/MergeSort/test_merge_sort.i: Algorithms/MergeSort/test_merge_sort.cpp.i
.PHONY : Algorithms/MergeSort/test_merge_sort.i

# target to preprocess a source file
Algorithms/MergeSort/test_merge_sort.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_merge_sort.dir/build.make CMakeFiles/test_merge_sort.dir/Algorithms/MergeSort/test_merge_sort.cpp.i
.PHONY : Algorithms/MergeSort/test_merge_sort.cpp.i

Algorithms/MergeSort/test_merge_sort.s: Algorithms/MergeSort/test_merge_sort.cpp.s
.PHONY : Algorithms/MergeSort/test_merge_sort.s

# target to generate assembly for a file
Algorithms/MergeSort/test_merge_sort.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_merge_sort.dir/build.make CMakeFiles/test_merge_sort.dir/Algorithms/MergeSort/test_merge_sort.cpp.s
.PHONY : Algorithms/MergeSort/test_merge_sort.cpp.s

Algorithms/MergeSortExternal/main.o: Algorithms/MergeSortExternal/main.cpp.o
.PHONY : Algorithms/MergeSortExternal/main.o

# target to build an object file
Algorithms/MergeSortExternal/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/merge_sort_external_main.dir/build.make CMakeFiles/merge_sort_external_main.dir/Algorithms/MergeSortExternal/main.cpp.o
.PHONY : Algorithms/MergeSortExternal/main.cpp.o

Algorithms/MergeSortExternal/main.i: Algorithms/MergeSortExternal/main.cpp.i
.PHONY : Algorithms/MergeSortExternal/main.i

# target to preprocess a source file
Algorithms/MergeSortExternal/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/merge_sort_external_main.dir/build.make CMakeFiles/merge_sort_external_main.dir/Algorithms/MergeSortExternal/main.cpp.i
.PHONY : Algorithms/MergeSortExternal/main.cpp.i

Algorithms/MergeSortExternal/main.s: Algorithms/MergeSortExternal/main.cpp.s
.PHONY : Algorithms/MergeSortExternal/main.s

# target to generate assembly for a file
Algorithms/MergeSortExternal/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/merge_sort_external_main.dir/build.make CMakeFiles/merge_sort_external_main.dir/Algorithms/MergeSortExternal/main.cpp.s
.PHONY : Algorithms/MergeSortExternal/main.cpp.s

Algorithms/QuickSort/main.o: Algorithms/QuickSort/main.cpp.o
.PHONY : Algorithms/QuickSort/main.o

# target to build an object file
Algorithms/QuickSort/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quick_sort_main.dir/build.make CMakeFiles/quick_sort_main.dir/Algorithms/QuickSort/main.cpp.o
.PHONY : Algorithms/QuickSort/main.cpp.o

Algorithms/QuickSort/main.i: Algorithms/QuickSort/main.cpp.i
.PHONY : Algorithms/QuickSort/main.i

# target to preprocess a source file
Algorithms/QuickSort/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quick_sort_main.dir/build.make CMakeFiles/quick_sort_main.dir/Algorithms/QuickSort/main.cpp.i
.PHONY : Algorithms/QuickSort/main.cpp.i

Algorithms/QuickSort/main.s: Algorithms/QuickSort/main.cpp.s
.PHONY : Algorithms/QuickSort/main.s

# target to generate assembly for a file
Algorithms/QuickSort/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quick_sort_main.dir/build.make CMakeFiles/quick_sort_main.dir/Algorithms/QuickSort/main.cpp.s
.PHONY : Algorithms/QuickSort/main.cpp.s

Algorithms/QuickSort/quick_sort.o: Algorithms/QuickSort/quick_sort.cpp.o
.PHONY : Algorithms/QuickSort/quick_sort.o

# target to build an object file
Algorithms/QuickSort/quick_sort.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quick_sort.dir/build.make CMakeFiles/quick_sort.dir/Algorithms/QuickSort/quick_sort.cpp.o
.PHONY : Algorithms/QuickSort/quick_sort.cpp.o

Algorithms/QuickSort/quick_sort.i: Algorithms/QuickSort/quick_sort.cpp.i
.PHONY : Algorithms/QuickSort/quick_sort.i

# target to preprocess a source file
Algorithms/QuickSort/quick_sort.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quick_sort.dir/build.make CMakeFiles/quick_sort.dir/Algorithms/QuickSort/quick_sort.cpp.i
.PHONY : Algorithms/QuickSort/quick_sort.cpp.i

Algorithms/QuickSort/quick_sort.s: Algorithms/QuickSort/quick_sort.cpp.s
.PHONY : Algorithms/QuickSort/quick_sort.s

# target to generate assembly for a file
Algorithms/QuickSort/quick_sort.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quick_sort.dir/build.make CMakeFiles/quick_sort.dir/Algorithms/QuickSort/quick_sort.cpp.s
.PHONY : Algorithms/QuickSort/quick_sort.cpp.s

DataStructure/BinaryTree/binary_tree.o: DataStructure/BinaryTree/binary_tree.cpp.o
.PHONY : DataStructure/BinaryTree/binary_tree.o

# target to build an object file
DataStructure/BinaryTree/binary_tree.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary_tree.dir/build.make CMakeFiles/binary_tree.dir/DataStructure/BinaryTree/binary_tree.cpp.o
.PHONY : DataStructure/BinaryTree/binary_tree.cpp.o

DataStructure/BinaryTree/binary_tree.i: DataStructure/BinaryTree/binary_tree.cpp.i
.PHONY : DataStructure/BinaryTree/binary_tree.i

# target to preprocess a source file
DataStructure/BinaryTree/binary_tree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary_tree.dir/build.make CMakeFiles/binary_tree.dir/DataStructure/BinaryTree/binary_tree.cpp.i
.PHONY : DataStructure/BinaryTree/binary_tree.cpp.i

DataStructure/BinaryTree/binary_tree.s: DataStructure/BinaryTree/binary_tree.cpp.s
.PHONY : DataStructure/BinaryTree/binary_tree.s

# target to generate assembly for a file
DataStructure/BinaryTree/binary_tree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary_tree.dir/build.make CMakeFiles/binary_tree.dir/DataStructure/BinaryTree/binary_tree.cpp.s
.PHONY : DataStructure/BinaryTree/binary_tree.cpp.s

DataStructure/BinaryTree/main.o: DataStructure/BinaryTree/main.cpp.o
.PHONY : DataStructure/BinaryTree/main.o

# target to build an object file
DataStructure/BinaryTree/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary_tree_main.dir/build.make CMakeFiles/binary_tree_main.dir/DataStructure/BinaryTree/main.cpp.o
.PHONY : DataStructure/BinaryTree/main.cpp.o

DataStructure/BinaryTree/main.i: DataStructure/BinaryTree/main.cpp.i
.PHONY : DataStructure/BinaryTree/main.i

# target to preprocess a source file
DataStructure/BinaryTree/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary_tree_main.dir/build.make CMakeFiles/binary_tree_main.dir/DataStructure/BinaryTree/main.cpp.i
.PHONY : DataStructure/BinaryTree/main.cpp.i

DataStructure/BinaryTree/main.s: DataStructure/BinaryTree/main.cpp.s
.PHONY : DataStructure/BinaryTree/main.s

# target to generate assembly for a file
DataStructure/BinaryTree/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary_tree_main.dir/build.make CMakeFiles/binary_tree_main.dir/DataStructure/BinaryTree/main.cpp.s
.PHONY : DataStructure/BinaryTree/main.cpp.s

DataStructure/HashTable/main.o: DataStructure/HashTable/main.cpp.o
.PHONY : DataStructure/HashTable/main.o

# target to build an object file
DataStructure/HashTable/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mrroot501_hash_table_main.dir/build.make CMakeFiles/mrroot501_hash_table_main.dir/DataStructure/HashTable/main.cpp.o
.PHONY : DataStructure/HashTable/main.cpp.o

DataStructure/HashTable/main.i: DataStructure/HashTable/main.cpp.i
.PHONY : DataStructure/HashTable/main.i

# target to preprocess a source file
DataStructure/HashTable/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mrroot501_hash_table_main.dir/build.make CMakeFiles/mrroot501_hash_table_main.dir/DataStructure/HashTable/main.cpp.i
.PHONY : DataStructure/HashTable/main.cpp.i

DataStructure/HashTable/main.s: DataStructure/HashTable/main.cpp.s
.PHONY : DataStructure/HashTable/main.s

# target to generate assembly for a file
DataStructure/HashTable/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mrroot501_hash_table_main.dir/build.make CMakeFiles/mrroot501_hash_table_main.dir/DataStructure/HashTable/main.cpp.s
.PHONY : DataStructure/HashTable/main.cpp.s

DataStructure/HashTable/mrroot501_hash_table.o: DataStructure/HashTable/mrroot501_hash_table.cpp.o
.PHONY : DataStructure/HashTable/mrroot501_hash_table.o

# target to build an object file
DataStructure/HashTable/mrroot501_hash_table.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mrroot501_hash_table.dir/build.make CMakeFiles/mrroot501_hash_table.dir/DataStructure/HashTable/mrroot501_hash_table.cpp.o
.PHONY : DataStructure/HashTable/mrroot501_hash_table.cpp.o

DataStructure/HashTable/mrroot501_hash_table.i: DataStructure/HashTable/mrroot501_hash_table.cpp.i
.PHONY : DataStructure/HashTable/mrroot501_hash_table.i

# target to preprocess a source file
DataStructure/HashTable/mrroot501_hash_table.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mrroot501_hash_table.dir/build.make CMakeFiles/mrroot501_hash_table.dir/DataStructure/HashTable/mrroot501_hash_table.cpp.i
.PHONY : DataStructure/HashTable/mrroot501_hash_table.cpp.i

DataStructure/HashTable/mrroot501_hash_table.s: DataStructure/HashTable/mrroot501_hash_table.cpp.s
.PHONY : DataStructure/HashTable/mrroot501_hash_table.s

# target to generate assembly for a file
DataStructure/HashTable/mrroot501_hash_table.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mrroot501_hash_table.dir/build.make CMakeFiles/mrroot501_hash_table.dir/DataStructure/HashTable/mrroot501_hash_table.cpp.s
.PHONY : DataStructure/HashTable/mrroot501_hash_table.cpp.s

DataStructure/LinkedList/linked_list.o: DataStructure/LinkedList/linked_list.cpp.o
.PHONY : DataStructure/LinkedList/linked_list.o

# target to build an object file
DataStructure/LinkedList/linked_list.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linked_list.dir/build.make CMakeFiles/linked_list.dir/DataStructure/LinkedList/linked_list.cpp.o
.PHONY : DataStructure/LinkedList/linked_list.cpp.o

DataStructure/LinkedList/linked_list.i: DataStructure/LinkedList/linked_list.cpp.i
.PHONY : DataStructure/LinkedList/linked_list.i

# target to preprocess a source file
DataStructure/LinkedList/linked_list.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linked_list.dir/build.make CMakeFiles/linked_list.dir/DataStructure/LinkedList/linked_list.cpp.i
.PHONY : DataStructure/LinkedList/linked_list.cpp.i

DataStructure/LinkedList/linked_list.s: DataStructure/LinkedList/linked_list.cpp.s
.PHONY : DataStructure/LinkedList/linked_list.s

# target to generate assembly for a file
DataStructure/LinkedList/linked_list.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linked_list.dir/build.make CMakeFiles/linked_list.dir/DataStructure/LinkedList/linked_list.cpp.s
.PHONY : DataStructure/LinkedList/linked_list.cpp.s

DataStructure/LinkedList/main.o: DataStructure/LinkedList/main.cpp.o
.PHONY : DataStructure/LinkedList/main.o

# target to build an object file
DataStructure/LinkedList/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linked_list_main.dir/build.make CMakeFiles/linked_list_main.dir/DataStructure/LinkedList/main.cpp.o
.PHONY : DataStructure/LinkedList/main.cpp.o

DataStructure/LinkedList/main.i: DataStructure/LinkedList/main.cpp.i
.PHONY : DataStructure/LinkedList/main.i

# target to preprocess a source file
DataStructure/LinkedList/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linked_list_main.dir/build.make CMakeFiles/linked_list_main.dir/DataStructure/LinkedList/main.cpp.i
.PHONY : DataStructure/LinkedList/main.cpp.i

DataStructure/LinkedList/main.s: DataStructure/LinkedList/main.cpp.s
.PHONY : DataStructure/LinkedList/main.s

# target to generate assembly for a file
DataStructure/LinkedList/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linked_list_main.dir/build.make CMakeFiles/linked_list_main.dir/DataStructure/LinkedList/main.cpp.s
.PHONY : DataStructure/LinkedList/main.cpp.s

DataStructure/SegmentTree/main.o: DataStructure/SegmentTree/main.cpp.o
.PHONY : DataStructure/SegmentTree/main.o

# target to build an object file
DataStructure/SegmentTree/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/segment_tree_main.dir/build.make CMakeFiles/segment_tree_main.dir/DataStructure/SegmentTree/main.cpp.o
.PHONY : DataStructure/SegmentTree/main.cpp.o

DataStructure/SegmentTree/main.i: DataStructure/SegmentTree/main.cpp.i
.PHONY : DataStructure/SegmentTree/main.i

# target to preprocess a source file
DataStructure/SegmentTree/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/segment_tree_main.dir/build.make CMakeFiles/segment_tree_main.dir/DataStructure/SegmentTree/main.cpp.i
.PHONY : DataStructure/SegmentTree/main.cpp.i

DataStructure/SegmentTree/main.s: DataStructure/SegmentTree/main.cpp.s
.PHONY : DataStructure/SegmentTree/main.s

# target to generate assembly for a file
DataStructure/SegmentTree/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/segment_tree_main.dir/build.make CMakeFiles/segment_tree_main.dir/DataStructure/SegmentTree/main.cpp.s
.PHONY : DataStructure/SegmentTree/main.cpp.s

DataStructure/SegmentTree/segment_tree.o: DataStructure/SegmentTree/segment_tree.cpp.o
.PHONY : DataStructure/SegmentTree/segment_tree.o

# target to build an object file
DataStructure/SegmentTree/segment_tree.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/segment_tree.dir/build.make CMakeFiles/segment_tree.dir/DataStructure/SegmentTree/segment_tree.cpp.o
.PHONY : DataStructure/SegmentTree/segment_tree.cpp.o

DataStructure/SegmentTree/segment_tree.i: DataStructure/SegmentTree/segment_tree.cpp.i
.PHONY : DataStructure/SegmentTree/segment_tree.i

# target to preprocess a source file
DataStructure/SegmentTree/segment_tree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/segment_tree.dir/build.make CMakeFiles/segment_tree.dir/DataStructure/SegmentTree/segment_tree.cpp.i
.PHONY : DataStructure/SegmentTree/segment_tree.cpp.i

DataStructure/SegmentTree/segment_tree.s: DataStructure/SegmentTree/segment_tree.cpp.s
.PHONY : DataStructure/SegmentTree/segment_tree.s

# target to generate assembly for a file
DataStructure/SegmentTree/segment_tree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/segment_tree.dir/build.make CMakeFiles/segment_tree.dir/DataStructure/SegmentTree/segment_tree.cpp.s
.PHONY : DataStructure/SegmentTree/segment_tree.cpp.s

ProblemSolving/ExtraLongFactorial/main.o: ProblemSolving/ExtraLongFactorial/main.cpp.o
.PHONY : ProblemSolving/ExtraLongFactorial/main.o

# target to build an object file
ProblemSolving/ExtraLongFactorial/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extra_long_factorial_main.dir/build.make CMakeFiles/extra_long_factorial_main.dir/ProblemSolving/ExtraLongFactorial/main.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_extra_long_factorial.dir/build.make CMakeFiles/test_extra_long_factorial.dir/ProblemSolving/ExtraLongFactorial/main.cpp.o
.PHONY : ProblemSolving/ExtraLongFactorial/main.cpp.o

ProblemSolving/ExtraLongFactorial/main.i: ProblemSolving/ExtraLongFactorial/main.cpp.i
.PHONY : ProblemSolving/ExtraLongFactorial/main.i

# target to preprocess a source file
ProblemSolving/ExtraLongFactorial/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extra_long_factorial_main.dir/build.make CMakeFiles/extra_long_factorial_main.dir/ProblemSolving/ExtraLongFactorial/main.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_extra_long_factorial.dir/build.make CMakeFiles/test_extra_long_factorial.dir/ProblemSolving/ExtraLongFactorial/main.cpp.i
.PHONY : ProblemSolving/ExtraLongFactorial/main.cpp.i

ProblemSolving/ExtraLongFactorial/main.s: ProblemSolving/ExtraLongFactorial/main.cpp.s
.PHONY : ProblemSolving/ExtraLongFactorial/main.s

# target to generate assembly for a file
ProblemSolving/ExtraLongFactorial/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/extra_long_factorial_main.dir/build.make CMakeFiles/extra_long_factorial_main.dir/ProblemSolving/ExtraLongFactorial/main.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_extra_long_factorial.dir/build.make CMakeFiles/test_extra_long_factorial.dir/ProblemSolving/ExtraLongFactorial/main.cpp.s
.PHONY : ProblemSolving/ExtraLongFactorial/main.cpp.s

ProblemSolving/FindLargestValueInTreeRow/main.o: ProblemSolving/FindLargestValueInTreeRow/main.cpp.o
.PHONY : ProblemSolving/FindLargestValueInTreeRow/main.o

# target to build an object file
ProblemSolving/FindLargestValueInTreeRow/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_find_largest_value_in_tree_row.dir/build.make CMakeFiles/test_find_largest_value_in_tree_row.dir/ProblemSolving/FindLargestValueInTreeRow/main.cpp.o
.PHONY : ProblemSolving/FindLargestValueInTreeRow/main.cpp.o

ProblemSolving/FindLargestValueInTreeRow/main.i: ProblemSolving/FindLargestValueInTreeRow/main.cpp.i
.PHONY : ProblemSolving/FindLargestValueInTreeRow/main.i

# target to preprocess a source file
ProblemSolving/FindLargestValueInTreeRow/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_find_largest_value_in_tree_row.dir/build.make CMakeFiles/test_find_largest_value_in_tree_row.dir/ProblemSolving/FindLargestValueInTreeRow/main.cpp.i
.PHONY : ProblemSolving/FindLargestValueInTreeRow/main.cpp.i

ProblemSolving/FindLargestValueInTreeRow/main.s: ProblemSolving/FindLargestValueInTreeRow/main.cpp.s
.PHONY : ProblemSolving/FindLargestValueInTreeRow/main.s

# target to generate assembly for a file
ProblemSolving/FindLargestValueInTreeRow/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_find_largest_value_in_tree_row.dir/build.make CMakeFiles/test_find_largest_value_in_tree_row.dir/ProblemSolving/FindLargestValueInTreeRow/main.cpp.s
.PHONY : ProblemSolving/FindLargestValueInTreeRow/main.cpp.s

ProblemSolving/LongestComonSubsequence/main.o: ProblemSolving/LongestComonSubsequence/main.cpp.o
.PHONY : ProblemSolving/LongestComonSubsequence/main.o

# target to build an object file
ProblemSolving/LongestComonSubsequence/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_longest_common_subsequence.dir/build.make CMakeFiles/test_longest_common_subsequence.dir/ProblemSolving/LongestComonSubsequence/main.cpp.o
.PHONY : ProblemSolving/LongestComonSubsequence/main.cpp.o

ProblemSolving/LongestComonSubsequence/main.i: ProblemSolving/LongestComonSubsequence/main.cpp.i
.PHONY : ProblemSolving/LongestComonSubsequence/main.i

# target to preprocess a source file
ProblemSolving/LongestComonSubsequence/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_longest_common_subsequence.dir/build.make CMakeFiles/test_longest_common_subsequence.dir/ProblemSolving/LongestComonSubsequence/main.cpp.i
.PHONY : ProblemSolving/LongestComonSubsequence/main.cpp.i

ProblemSolving/LongestComonSubsequence/main.s: ProblemSolving/LongestComonSubsequence/main.cpp.s
.PHONY : ProblemSolving/LongestComonSubsequence/main.s

# target to generate assembly for a file
ProblemSolving/LongestComonSubsequence/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_longest_common_subsequence.dir/build.make CMakeFiles/test_longest_common_subsequence.dir/ProblemSolving/LongestComonSubsequence/main.cpp.s
.PHONY : ProblemSolving/LongestComonSubsequence/main.cpp.s

ProblemSolving/LongestPalindromicSubstring/main.o: ProblemSolving/LongestPalindromicSubstring/main.cpp.o
.PHONY : ProblemSolving/LongestPalindromicSubstring/main.o

# target to build an object file
ProblemSolving/LongestPalindromicSubstring/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_longest_palindromic_substring.dir/build.make CMakeFiles/test_longest_palindromic_substring.dir/ProblemSolving/LongestPalindromicSubstring/main.cpp.o
.PHONY : ProblemSolving/LongestPalindromicSubstring/main.cpp.o

ProblemSolving/LongestPalindromicSubstring/main.i: ProblemSolving/LongestPalindromicSubstring/main.cpp.i
.PHONY : ProblemSolving/LongestPalindromicSubstring/main.i

# target to preprocess a source file
ProblemSolving/LongestPalindromicSubstring/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_longest_palindromic_substring.dir/build.make CMakeFiles/test_longest_palindromic_substring.dir/ProblemSolving/LongestPalindromicSubstring/main.cpp.i
.PHONY : ProblemSolving/LongestPalindromicSubstring/main.cpp.i

ProblemSolving/LongestPalindromicSubstring/main.s: ProblemSolving/LongestPalindromicSubstring/main.cpp.s
.PHONY : ProblemSolving/LongestPalindromicSubstring/main.s

# target to generate assembly for a file
ProblemSolving/LongestPalindromicSubstring/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_longest_palindromic_substring.dir/build.make CMakeFiles/test_longest_palindromic_substring.dir/ProblemSolving/LongestPalindromicSubstring/main.cpp.s
.PHONY : ProblemSolving/LongestPalindromicSubstring/main.cpp.s

ProblemSolving/RangeSumQueriesWithoutUpdates/main.o: ProblemSolving/RangeSumQueriesWithoutUpdates/main.cpp.o
.PHONY : ProblemSolving/RangeSumQueriesWithoutUpdates/main.o

# target to build an object file
ProblemSolving/RangeSumQueriesWithoutUpdates/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_range_sum_queries_without_updates.dir/build.make CMakeFiles/test_range_sum_queries_without_updates.dir/ProblemSolving/RangeSumQueriesWithoutUpdates/main.cpp.o
.PHONY : ProblemSolving/RangeSumQueriesWithoutUpdates/main.cpp.o

ProblemSolving/RangeSumQueriesWithoutUpdates/main.i: ProblemSolving/RangeSumQueriesWithoutUpdates/main.cpp.i
.PHONY : ProblemSolving/RangeSumQueriesWithoutUpdates/main.i

# target to preprocess a source file
ProblemSolving/RangeSumQueriesWithoutUpdates/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_range_sum_queries_without_updates.dir/build.make CMakeFiles/test_range_sum_queries_without_updates.dir/ProblemSolving/RangeSumQueriesWithoutUpdates/main.cpp.i
.PHONY : ProblemSolving/RangeSumQueriesWithoutUpdates/main.cpp.i

ProblemSolving/RangeSumQueriesWithoutUpdates/main.s: ProblemSolving/RangeSumQueriesWithoutUpdates/main.cpp.s
.PHONY : ProblemSolving/RangeSumQueriesWithoutUpdates/main.s

# target to generate assembly for a file
ProblemSolving/RangeSumQueriesWithoutUpdates/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_range_sum_queries_without_updates.dir/build.make CMakeFiles/test_range_sum_queries_without_updates.dir/ProblemSolving/RangeSumQueriesWithoutUpdates/main.cpp.s
.PHONY : ProblemSolving/RangeSumQueriesWithoutUpdates/main.cpp.s

ProblemSolving/ShortestPathInBinaryMatrix/main.o: ProblemSolving/ShortestPathInBinaryMatrix/main.cpp.o
.PHONY : ProblemSolving/ShortestPathInBinaryMatrix/main.o

# target to build an object file
ProblemSolving/ShortestPathInBinaryMatrix/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_shortest_path_in_binary_matrix.dir/build.make CMakeFiles/test_shortest_path_in_binary_matrix.dir/ProblemSolving/ShortestPathInBinaryMatrix/main.cpp.o
.PHONY : ProblemSolving/ShortestPathInBinaryMatrix/main.cpp.o

ProblemSolving/ShortestPathInBinaryMatrix/main.i: ProblemSolving/ShortestPathInBinaryMatrix/main.cpp.i
.PHONY : ProblemSolving/ShortestPathInBinaryMatrix/main.i

# target to preprocess a source file
ProblemSolving/ShortestPathInBinaryMatrix/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_shortest_path_in_binary_matrix.dir/build.make CMakeFiles/test_shortest_path_in_binary_matrix.dir/ProblemSolving/ShortestPathInBinaryMatrix/main.cpp.i
.PHONY : ProblemSolving/ShortestPathInBinaryMatrix/main.cpp.i

ProblemSolving/ShortestPathInBinaryMatrix/main.s: ProblemSolving/ShortestPathInBinaryMatrix/main.cpp.s
.PHONY : ProblemSolving/ShortestPathInBinaryMatrix/main.s

# target to generate assembly for a file
ProblemSolving/ShortestPathInBinaryMatrix/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_shortest_path_in_binary_matrix.dir/build.make CMakeFiles/test_shortest_path_in_binary_matrix.dir/ProblemSolving/ShortestPathInBinaryMatrix/main.cpp.s
.PHONY : ProblemSolving/ShortestPathInBinaryMatrix/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... googletest"
	@echo "... binary_tree"
	@echo "... binary_tree_main"
	@echo "... extra_long_factorial_main"
	@echo "... heap_sort"
	@echo "... linked_list"
	@echo "... linked_list_main"
	@echo "... merge_sort"
	@echo "... merge_sort_external_main"
	@echo "... mrroot501_hash_table"
	@echo "... mrroot501_hash_table_main"
	@echo "... quick_sort"
	@echo "... quick_sort_main"
	@echo "... segment_tree"
	@echo "... segment_tree_main"
	@echo "... test_extra_long_factorial"
	@echo "... test_find_largest_value_in_tree_row"
	@echo "... test_heap_sort"
	@echo "... test_longest_common_subsequence"
	@echo "... test_longest_palindromic_substring"
	@echo "... test_merge_sort"
	@echo "... test_range_sum_queries_without_updates"
	@echo "... test_shortest_path_in_binary_matrix"
	@echo "... Algorithms/HeapSort/heap_sort.o"
	@echo "... Algorithms/HeapSort/heap_sort.i"
	@echo "... Algorithms/HeapSort/heap_sort.s"
	@echo "... Algorithms/HeapSort/test_heap_sort.o"
	@echo "... Algorithms/HeapSort/test_heap_sort.i"
	@echo "... Algorithms/HeapSort/test_heap_sort.s"
	@echo "... Algorithms/MergeSort/merge_sort.o"
	@echo "... Algorithms/MergeSort/merge_sort.i"
	@echo "... Algorithms/MergeSort/merge_sort.s"
	@echo "... Algorithms/MergeSort/test_merge_sort.o"
	@echo "... Algorithms/MergeSort/test_merge_sort.i"
	@echo "... Algorithms/MergeSort/test_merge_sort.s"
	@echo "... Algorithms/MergeSortExternal/main.o"
	@echo "... Algorithms/MergeSortExternal/main.i"
	@echo "... Algorithms/MergeSortExternal/main.s"
	@echo "... Algorithms/QuickSort/main.o"
	@echo "... Algorithms/QuickSort/main.i"
	@echo "... Algorithms/QuickSort/main.s"
	@echo "... Algorithms/QuickSort/quick_sort.o"
	@echo "... Algorithms/QuickSort/quick_sort.i"
	@echo "... Algorithms/QuickSort/quick_sort.s"
	@echo "... DataStructure/BinaryTree/binary_tree.o"
	@echo "... DataStructure/BinaryTree/binary_tree.i"
	@echo "... DataStructure/BinaryTree/binary_tree.s"
	@echo "... DataStructure/BinaryTree/main.o"
	@echo "... DataStructure/BinaryTree/main.i"
	@echo "... DataStructure/BinaryTree/main.s"
	@echo "... DataStructure/HashTable/main.o"
	@echo "... DataStructure/HashTable/main.i"
	@echo "... DataStructure/HashTable/main.s"
	@echo "... DataStructure/HashTable/mrroot501_hash_table.o"
	@echo "... DataStructure/HashTable/mrroot501_hash_table.i"
	@echo "... DataStructure/HashTable/mrroot501_hash_table.s"
	@echo "... DataStructure/LinkedList/linked_list.o"
	@echo "... DataStructure/LinkedList/linked_list.i"
	@echo "... DataStructure/LinkedList/linked_list.s"
	@echo "... DataStructure/LinkedList/main.o"
	@echo "... DataStructure/LinkedList/main.i"
	@echo "... DataStructure/LinkedList/main.s"
	@echo "... DataStructure/SegmentTree/main.o"
	@echo "... DataStructure/SegmentTree/main.i"
	@echo "... DataStructure/SegmentTree/main.s"
	@echo "... DataStructure/SegmentTree/segment_tree.o"
	@echo "... DataStructure/SegmentTree/segment_tree.i"
	@echo "... DataStructure/SegmentTree/segment_tree.s"
	@echo "... ProblemSolving/ExtraLongFactorial/main.o"
	@echo "... ProblemSolving/ExtraLongFactorial/main.i"
	@echo "... ProblemSolving/ExtraLongFactorial/main.s"
	@echo "... ProblemSolving/FindLargestValueInTreeRow/main.o"
	@echo "... ProblemSolving/FindLargestValueInTreeRow/main.i"
	@echo "... ProblemSolving/FindLargestValueInTreeRow/main.s"
	@echo "... ProblemSolving/LongestComonSubsequence/main.o"
	@echo "... ProblemSolving/LongestComonSubsequence/main.i"
	@echo "... ProblemSolving/LongestComonSubsequence/main.s"
	@echo "... ProblemSolving/LongestPalindromicSubstring/main.o"
	@echo "... ProblemSolving/LongestPalindromicSubstring/main.i"
	@echo "... ProblemSolving/LongestPalindromicSubstring/main.s"
	@echo "... ProblemSolving/RangeSumQueriesWithoutUpdates/main.o"
	@echo "... ProblemSolving/RangeSumQueriesWithoutUpdates/main.i"
	@echo "... ProblemSolving/RangeSumQueriesWithoutUpdates/main.s"
	@echo "... ProblemSolving/ShortestPathInBinaryMatrix/main.o"
	@echo "... ProblemSolving/ShortestPathInBinaryMatrix/main.i"
	@echo "... ProblemSolving/ShortestPathInBinaryMatrix/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

