include ../Makefile

ProjectName := DataStructure

BinaryTree:
	@$(call run_module)

LinkedList:
	@$(call run_module)

Stack:
	@$(call run_module)

SegmentTree:
	@$(call run_module)

clean:
	@$(call runClean)

validateTargets: Makefile
	@$(call validateTargets)

.PHONY: help
all: help
help: Makefile
	@$(call runHelp)
