include ../Makefile

ProjectName := DataStructure

BinaryTree:
	@$(call runTarget)

LinkedList:
	@$(call runTarget)

Stack:
	@$(call runTarget)

SegmentTree:
	@$(call runTarget)

HashTable:
	@$(call runTarget)

clean:
	@$(call runClean)

validateTargets: Makefile
	@$(call validateTargets)

.PHONY: help
all: help
help: Makefile
	@$(call runHelp)
