include ../Makefile

ProjectName := Algorithms

BFS:
	@$(call run_module)

DFS:
	@$(call run_module)

QuickSort:
	@$(call run_module)

BoyerMoore:
	@$(call run_module)

BinarySearch:
	@$(call run_module)

Dijkstra:
	@$(call run_module)

MergeSort:
	@$(call run_module)

MergeSortExternal:
	@$(call run_module)

KruskalMST:
	@$(call run_module)

HeapSort:
	@$(call run_module)

clean:
	@$(call runClean)

validateTargets: Makefile
	@$(call validateTargets)

.PHONY: help
all: help
help: Makefile
	@$(call runHelp)
