include ../Makefile

ProjectName := ProblemSolving

FindLargestValueInTreeRow:
	@$(call run_module)

HanoiTower:
	@$(call run_module)

LongestPalindromicSubstring:
	@$(call run_module)

MaximumSumSubarray:
	@$(call run_module)

MergeTwoSortedArrays:
	@$(call run_module)

MergeKSortedArrays:
	@$(call run_module)

RadioTransmitters:
	@$(call run_module)

ReadLargeFile:
	@$(call run_module)

RotateImage:
	@$(call run_module)

SmallestSubarrayWithKDistinctNumbers:
	@$(call run_module)

ExtraLongFactorial:
	@$(call run_module)

clean:
	@$(call runClean)

validateTargets: Makefile
	@$(call validateTargets)

.PHONY: help
all: help
help: Makefile
	@$(call runHelp)
