include ../Makefile

ProjectName := ProblemSolving

FindLargestValueInTreeRow:
	@$(call runTarget)

HanoiTower:
	@$(call runTarget)

LongestPalindromicSubstring:
	@$(call runTarget)

MaximumSumSubarray:
	@$(call runTarget)

MergeTwoSortedArrays:
	@$(call runTarget)

MergeKSortedArrays:
	@$(call runTarget)

RadioTransmitters:
	@$(call runTarget)

ReadLargeFile:
	@$(call runTarget)

RotateImage:
	@$(call runTarget)

SmallestSubarrayWithKDistinctNumbers:
	@$(call runTarget)

ExtraLongFactorial:
	@$(call runTarget)

RangeSumQueriesWithoutUpdates:
	@$(call runTarget)

ShortestPathInBinaryMatrix:
	@$(call runTarget)

LongestComonSubsequence:
	@$(call runTarget)

clean:
	@$(call runClean)

validateTargets: Makefile
	@$(call validateTargets)

.PHONY: help
all: help
help: Makefile
	@$(call runHelp)
