name: Cpp-Core
  
on:
  push

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Validate ref_name
      run: make check_ref_name REF_TYPE=${{ github.ref_type }} REF_NAME=${{ github.ref_name }}

    - uses: bazelbuild/setup-bazelisk@v3

    - name: Get changed files
      id: changed-files
      uses: jitterbit/get-changed-files@v1
      with:
        format: 'csv'

    - name: Run CI
      id: run-ci
      run: make run_ci CHANGES=${{ steps.changed-files.outputs.all }}
    
    - name: Run all tests
      id: run-all-tests
      run: |
        if [ ${{ github.event.head_commit.message }} == "[run-all-tests]" ];
        then
          make test
        fi
        
